"""
Memory Book Generator - Creates a beautiful static website from user's memories
"""

import os
import json
from pathlib import Path
from typing import List, Dict, Any, Optional
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class MemoryBookGenerator:
    """Generates a static HTML website from user's memories"""

    def __init__(self, output_dir: Path = None):
        """
        Initialize memory book generator
        
        Args:
            output_dir: Directory to output the static site (defaults to ./memory_books)
        """
        if output_dir is None:
            output_dir = Path(__file__).parent.parent / "memory_books"
        
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_memory_book(
        self,
        user_address: str,
        user_name: str,
        memories: List[Dict[str, Any]],
        ens_domain: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate a memory book static website
        
        Args:
            user_address: User's wallet address
            user_name: User's name
            memories: List of memory objects with:
                - title: str
                - description: str
                - date: str
                - type: str (photo/video/letter/audio)
                - ipfsHash: str
            ens_domain: Optional ENS domain for the memory book
            
        Returns:
            Dictionary with:
                - html_path: Path to generated HTML file
                - ipfs_hash: IPFS hash of the site
                - ens_domain: ENS domain if provided
        """
        # Create user-specific directory
        user_dir = self.output_dir / user_address.lower()
        user_dir.mkdir(parents=True, exist_ok=True)

        # Generate HTML
        html_content = self._generate_html(user_name, memories, ens_domain)
        
        # Save HTML file
        html_path = user_dir / "index.html"
        html_path.write_text(html_content, encoding="utf-8")

        # Generate assets directory
        assets_dir = user_dir / "assets"
        assets_dir.mkdir(exist_ok=True)

        # Copy CSS and JS
        self._generate_css(assets_dir)
        self._generate_js(assets_dir)

        logger.info(f"Memory book generated at {html_path}")

        return {
            "html_path": str(html_path),
            "directory": str(user_dir),
            "ens_domain": ens_domain,
        }

    def _generate_html(self, user_name: str, memories: List[Dict[str, Any]], ens_domain: Optional[str]) -> str:
        """Generate the main HTML content"""
        memories_html = ""
        for memory in memories:
            memories_html += self._generate_memory_card(memory)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{user_name}'s Memory Book</title>
    <link rel="stylesheet" href="assets/style.css">
    <meta name="description" content="A digital memory book preserving {user_name}'s legacy">
</head>
<body>
    <div class="container">
        <header class="header">
            <h1 class="title">{user_name}'s Memory Book</h1>
            <p class="subtitle">A collection of memories, preserved forever on the blockchain</p>
            {f'<p class="ens-domain">🌐 {ens_domain}</p>' if ens_domain else ''}
        </header>

        <div class="memories-grid">
            {memories_html}
        </div>

        <footer class="footer">
            <p>Generated by Project Charon • Preserved on IPFS</p>
            <p>This memory book was created automatically from your digital legacy</p>
        </footer>
    </div>

    <script src="assets/script.js"></script>
</body>
</html>"""

    def _generate_memory_card(self, memory: Dict[str, Any]) -> str:
        """Generate HTML for a single memory card"""
        date_formatted = datetime.fromisoformat(memory.get("date", "")).strftime("%B %d, %Y") if memory.get("date") else "Unknown Date"
        
        media_html = ""
        if memory.get("type") == "photo" and memory.get("ipfsHash"):
            media_html = f'<img src="https://ipfs.io/ipfs/{memory["ipfsHash"]}" alt="{memory.get("title", "Memory")}" class="memory-media">'
        elif memory.get("type") == "video" and memory.get("ipfsHash"):
            media_html = f'<video src="https://ipfs.io/ipfs/{memory["ipfsHash"]}" controls class="memory-media"></video>'
        elif memory.get("type") == "audio" and memory.get("ipfsHash"):
            media_html = f'<audio src="https://ipfs.io/ipfs/{memory["ipfsHash"]}" controls class="memory-media"></audio>'

        return f"""
        <div class="memory-card">
            {media_html}
            <div class="memory-content">
                <h2 class="memory-title">{memory.get("title", "Untitled Memory")}</h2>
                <p class="memory-date">{date_formatted}</p>
                <p class="memory-description">{memory.get("description", "")}</p>
            </div>
        </div>
        """

    def _generate_css(self, assets_dir: Path) -> None:
        """Generate CSS file"""
        css_content = """
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: #333;
    line-height: 1.6;
    min-height: 100vh;
    padding: 20px;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
}

.header {
    text-align: center;
    padding: 60px 20px;
    color: white;
}

.title {
    font-size: 3.5rem;
    font-weight: 700;
    margin-bottom: 10px;
    text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
}

.subtitle {
    font-size: 1.3rem;
    opacity: 0.9;
    margin-bottom: 10px;
}

.ens-domain {
    font-size: 1rem;
    opacity: 0.8;
    margin-top: 10px;
}

.memories-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
    gap: 30px;
    padding: 40px 20px;
}

.memory-card {
    background: white;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 10px 30px rgba(0,0,0,0.2);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.memory-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 15px 40px rgba(0,0,0,0.3);
}

.memory-media {
    width: 100%;
    height: 250px;
    object-fit: cover;
    display: block;
}

.memory-content {
    padding: 25px;
}

.memory-title {
    font-size: 1.5rem;
    font-weight: 600;
    margin-bottom: 8px;
    color: #333;
}

.memory-date {
    font-size: 0.9rem;
    color: #666;
    margin-bottom: 12px;
}

.memory-description {
    font-size: 1rem;
    color: #555;
    line-height: 1.6;
}

.footer {
    text-align: center;
    padding: 40px 20px;
    color: white;
    opacity: 0.8;
}

.footer p {
    margin: 5px 0;
}

@media (max-width: 768px) {
    .title {
        font-size: 2.5rem;
    }
    
    .memories-grid {
        grid-template-columns: 1fr;
        padding: 20px 10px;
    }
}
"""
        (assets_dir / "style.css").write_text(css_content, encoding="utf-8")

    def _generate_js(self, assets_dir: Path) -> None:
        """Generate JavaScript file"""
        js_content = """
// Memory Book JavaScript
document.addEventListener('DOMContentLoaded', function() {
    // Add fade-in animation to cards
    const cards = document.querySelectorAll('.memory-card');
    cards.forEach((card, index) => {
        card.style.opacity = '0';
        card.style.transform = 'translateY(20px)';
        setTimeout(() => {
            card.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
            card.style.opacity = '1';
            card.style.transform = 'translateY(0)';
        }, index * 100);
    });
});
"""
        (assets_dir / "script.js").write_text(js_content, encoding="utf-8")

